site_name: maximiliankraft.github.io

theme: cinder
github_user: maximiliankraft
github_repo: maximiliankraft.github.io
github_banner: true
site_description: Diese Webseite stellt Unterrichtsmaterialien zur Verf√ºgung.

repo_url: https://github.com/maximiliankraft/maximiliankraft.github.io
edit_uri: edit/main/docs/
nav:
  - Livecode XP: https://livecodexp-evgpgtawgsbyfuff.swedencentral-01.azurewebsites.net/
